// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wdguqtkfrpxmjzygousk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndkZ3VxdGtmcnB4bWp6eWdvdXNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2NTU4NTUsImV4cCI6MjA1OTIzMTg1NX0.WkiqLvdg5Ik6giLdkTL0D1mE8LC3Aq22tTW4p40JGtA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);